// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErrorHighlighter
{
    static class Vsix
    {
        public const string Id = "0798393f-f7b0-4283-a36e-c57a73f031c4";
        public const string Name = "Error Catcher";
        public const string Description = @"The easiest way to make sure not to miss any errors or warnings in any code file.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "error, exception";
    }
}
